import React from 'react'
import Head from 'next/head'
import Link from 'next/link'
import { useState } from 'react'
import { GrMenu } from "react-icons/gr"
import {AiOutlineClose} from 'react-icons/ai'
function Navbar() {
  const [nav , setNav] = useState(true)

  function handleclick(){
   setNav(!nav)
  }
  function handler(){
    window.location="signin"
  }
  function started(e){
   window.location="start"
  }
  function rashbase(){
    window.location="/"
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='  flex justify-between pt-7 pr-5 border pb-5 pl-5 text-white'>
        <h2 onClick={rashbase} className='text-xl lg:text-3xl cursor-pointer text-blue-500 font-bold'><span className='text-orange-500 border border-orange-500'>RANSOM</span>Trade</h2>

        <div className={nav ? 'hidden':`flex gap-10 h-full  text-white leading-10 md:hidden p-5 font-semibold absolute flex-col top-20 left-0 right-0 bg-black text-xl link duration-500 ease-in ${nav ? 'top-100px': ""}`}>
        <Link href="explore">explore</Link>
        <Link href="learn">Learn</Link> 
        <Link href="individual">Individuals</Link>
        <Link href="/">Businesses</Link>
        <Link href="/">Developers</Link>
        <Link href="company">Company</Link>
        </div>

        <div className='justify-center lg:flex gap-5 z-10 hidden lg:block  text-black font-semibold '>
        <Link href="explore">explore</Link>
        <Link href="learn">Learn</Link>
        <Link href="individual">Individuals</Link>
        <Link href="/">Businesses</Link>
        <Link href="/">Developers</Link>
        <Link href="company">Company</Link>
        </div>

    <div className='flex  gap-5 '>
        <button className='text-black hidden lg:block hover:text-blue-500' onClick={handler}>Sign In</button>
        <button className='text-white bg-blue-500 p-2 rounded hover:bg-red hover:bg-black' onClick={started}>Get Started</button>

        <div className='text-2xl lg:hidden cursor-pointer' onClick={handleclick}>
        {nav ? <GrMenu/>: <AiOutlineClose className='text-black'/>}
      </div>
      </div>

</div>

    </div>
  )
}

export default Navbar